languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "TSV Mettauertal"

[params]
  displayName = "Deutsch"
  isoCode = "de"
  rtl = false
  dateFormat = "02.01.2006"
  logo = "img/logo_color.png"
  secondaryLogo = "img/logo_color_neg.png"
  description = "TSV Mettauertal"
  copyright = '© TSV Mettauertal'
